# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from Impactyn.Contracts.RuntimeService import V1_pb2 as Impactyn_dot_Contracts_dot_RuntimeService_dot_V1__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in Impactyn.Contracts.RuntimeService.V1_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RuntimeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Version = channel.unary_unary(
                '/Impactyn.Contracts.RuntimeService.V1.RuntimeService/Version',
                request_serializer=Impactyn_dot_Contracts_dot_RuntimeService_dot_V1__pb2.VersionRequest.SerializeToString,
                response_deserializer=Impactyn_dot_Contracts_dot_RuntimeService_dot_V1__pb2.VersionResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/Impactyn.Contracts.RuntimeService.V1.RuntimeService/Get',
                request_serializer=Impactyn_dot_Contracts_dot_RuntimeService_dot_V1__pb2.GetRequest.SerializeToString,
                response_deserializer=Impactyn_dot_Contracts_dot_RuntimeService_dot_V1__pb2.GetResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/Impactyn.Contracts.RuntimeService.V1.RuntimeService/Delete',
                request_serializer=Impactyn_dot_Contracts_dot_RuntimeService_dot_V1__pb2.DeleteRequest.SerializeToString,
                response_deserializer=Impactyn_dot_Contracts_dot_RuntimeService_dot_V1__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.Execute = channel.unary_unary(
                '/Impactyn.Contracts.RuntimeService.V1.RuntimeService/Execute',
                request_serializer=Impactyn_dot_Contracts_dot_RuntimeService_dot_V1__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=Impactyn_dot_Contracts_dot_RuntimeService_dot_V1__pb2.ExecuteResponse.FromString,
                _registered_method=True)
        self.CreateOrUpdate = channel.unary_unary(
                '/Impactyn.Contracts.RuntimeService.V1.RuntimeService/CreateOrUpdate',
                request_serializer=Impactyn_dot_Contracts_dot_RuntimeService_dot_V1__pb2.CreateOrUpdateRequest.SerializeToString,
                response_deserializer=Impactyn_dot_Contracts_dot_RuntimeService_dot_V1__pb2.CreateOrUpdateResponse.FromString,
                _registered_method=True)


class RuntimeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Version(self, request, context):
        """Version returns the runtime name, runtime version, and runtime API version.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Execute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateOrUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RuntimeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Version': grpc.unary_unary_rpc_method_handler(
                    servicer.Version,
                    request_deserializer=Impactyn_dot_Contracts_dot_RuntimeService_dot_V1__pb2.VersionRequest.FromString,
                    response_serializer=Impactyn_dot_Contracts_dot_RuntimeService_dot_V1__pb2.VersionResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=Impactyn_dot_Contracts_dot_RuntimeService_dot_V1__pb2.GetRequest.FromString,
                    response_serializer=Impactyn_dot_Contracts_dot_RuntimeService_dot_V1__pb2.GetResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=Impactyn_dot_Contracts_dot_RuntimeService_dot_V1__pb2.DeleteRequest.FromString,
                    response_serializer=Impactyn_dot_Contracts_dot_RuntimeService_dot_V1__pb2.DeleteResponse.SerializeToString,
            ),
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=Impactyn_dot_Contracts_dot_RuntimeService_dot_V1__pb2.ExecuteRequest.FromString,
                    response_serializer=Impactyn_dot_Contracts_dot_RuntimeService_dot_V1__pb2.ExecuteResponse.SerializeToString,
            ),
            'CreateOrUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOrUpdate,
                    request_deserializer=Impactyn_dot_Contracts_dot_RuntimeService_dot_V1__pb2.CreateOrUpdateRequest.FromString,
                    response_serializer=Impactyn_dot_Contracts_dot_RuntimeService_dot_V1__pb2.CreateOrUpdateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Impactyn.Contracts.RuntimeService.V1.RuntimeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Impactyn.Contracts.RuntimeService.V1.RuntimeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RuntimeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Version(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Impactyn.Contracts.RuntimeService.V1.RuntimeService/Version',
            Impactyn_dot_Contracts_dot_RuntimeService_dot_V1__pb2.VersionRequest.SerializeToString,
            Impactyn_dot_Contracts_dot_RuntimeService_dot_V1__pb2.VersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Impactyn.Contracts.RuntimeService.V1.RuntimeService/Get',
            Impactyn_dot_Contracts_dot_RuntimeService_dot_V1__pb2.GetRequest.SerializeToString,
            Impactyn_dot_Contracts_dot_RuntimeService_dot_V1__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Impactyn.Contracts.RuntimeService.V1.RuntimeService/Delete',
            Impactyn_dot_Contracts_dot_RuntimeService_dot_V1__pb2.DeleteRequest.SerializeToString,
            Impactyn_dot_Contracts_dot_RuntimeService_dot_V1__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Impactyn.Contracts.RuntimeService.V1.RuntimeService/Execute',
            Impactyn_dot_Contracts_dot_RuntimeService_dot_V1__pb2.ExecuteRequest.SerializeToString,
            Impactyn_dot_Contracts_dot_RuntimeService_dot_V1__pb2.ExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateOrUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Impactyn.Contracts.RuntimeService.V1.RuntimeService/CreateOrUpdate',
            Impactyn_dot_Contracts_dot_RuntimeService_dot_V1__pb2.CreateOrUpdateRequest.SerializeToString,
            Impactyn_dot_Contracts_dot_RuntimeService_dot_V1__pb2.CreateOrUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
